version: "2.0"

services:
  sword:
    build:
      context: ./sword
      dockerfile: Dockerfile
    command: ./run_web.sh
    volumes:
      - "./sword:/app"
    links:
      - db
    depends_on:
      - db
    ports:
      - "32642:32642"

  db:
    image: postgres:9.6
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/postgres/data
    volumes:
      - "data:/postgres/data"  # /var/lib/postgresql/data

volumes:
  data:

